Exam/R54_Ex_06_Mvc_Evidence/R54_Ex_06_Mvc_Evidence/ViewModels/ApplicantViewModel.cs
using R54_Ex_06_Mvc_Evidence.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace R54_Ex_06_Mvc_Evidence.ViewModels
{
    public class ApplicantViewModel
    {
        public int ApplicantId { get; set; }
        [Required, StringLength(40)]
        public string ApplicantName { get; set; }
        [Required, Column(TypeName = "date")]
        public DateTime BirthDate { get; set; }
        [EnumDataType(typeof(Gender))]
        public Gender Gender { get; set; }
        [Required, StringLength(30)]
        public string AppliedFor { get; set; }
        [Required]
        public HttpPostedFileBase Picture { get; set; }
        public bool IsReadyToWorkAnyWhere { get; set; }
        public virtual List<Qualification> Qualifications { get; set; } = new List<Qualification>();
    }
}

Exam/R54_Ex_06_Mvc_Evidence/R54_Ex_06_Mvc_Evidence/Controllers/ApplicantsController.cs
using R54_Ex_06_Mvc_Evidence.Models;
using R54_Ex_06_Mvc_Evidence.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
namespace R54_Ex_06_Mvc_Evidence.Controllers
{
    public class ApplicantsController : Controller
    {
        private readonly ApplicantDbContext db = new ApplicantDbContext();
        // GET: Applicants
        public ActionResult Index()
        {
            //Eager loading
            var data = db.Applicants.Include(x => x.Qualifications).AsNoTracking().ToList();
            return View(data);
        }
        public ActionResult Create()
        {
            ApplicantViewModel a =new ApplicantViewModel();
            a.Qualifications.Add(new Qualification { });
            return View(a);

        }
        [HttpPost]
        public ActionResult Create(ApplicantViewModel data, string act="")
        {
            if(act == "add")
            {
                data.Qualifications.Add(new Qualification { });
            }
            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring( act.IndexOf("_")+1));
                data.Qualifications.RemoveAt(index);
            }
            if(act=="insert")
            {
                if(ModelState.IsValid)
                {
                    var a = new  Applicant
                    {
                        ApplicantName = data.ApplicantName,
                        BirthDate = data.BirthDate,
                        AppliedFor = data.AppliedFor,
                        Gender = data.Gender,
                        IsReadyToWorkAnyWhere= data.IsReadyToWorkAnyWhere
                        
                    };
                    string ext = Path.GetExtension(data.Picture.FileName);
                    string fileName = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                    string savePath = Server.MapPath("~/Pictures/") + fileName;
                    data.Picture.SaveAs(savePath);
                    a.Picture = fileName;
                    foreach(var q in data.Qualifications)
                    {
                        a.Qualifications.Add(q);
                    }
                    db.Applicants.Add(a);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(data);
        }
        public ActionResult Edit(int id)
        {
            //explicit

            var x = db.Applicants.FirstOrDefault(a => a.ApplicantId == id);
            if (x == null) return new HttpNotFoundResult();
            db.Entry(x).Collection(q => q.Qualifications).Load();

            var data = new ApplicantEditModel
            {
                ApplicantId = x.ApplicantId,
                ApplicantName = x.ApplicantName,
                BirthDate = x.BirthDate,
                Gender = x.Gender,
                AppliedFor = x.AppliedFor,
                IsReadyToWorkAnyWhere = x.IsReadyToWorkAnyWhere,
                Qualifications = x.Qualifications.ToList()

            };
            ViewBag.CurrentPic = db.Applicants.FirstOrDefault(o => o.ApplicantId == id).Picture;

            return View(data);
        }
        [HttpPost]
        public ActionResult Edit(ApplicantEditModel data, string act = "")
        {
            if (act == "add")
            {
                data.Qualifications.Add(new Qualification { });
            }
            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                data.Qualifications.RemoveAt(index);
            }
            if (act == "update")
            {
                if (ModelState.IsValid)
                {
                    var a = db.Applicants.FirstOrDefault(x => x.ApplicantId == data.ApplicantId);

                    a.ApplicantName = data.ApplicantName;
                    a.BirthDate = data.BirthDate;
                    a.AppliedFor = data.AppliedFor;
                    a.Gender = data.Gender;
                    a.IsReadyToWorkAnyWhere = data.IsReadyToWorkAnyWhere;


                    if (data.Picture != null)
                    {
                        string ext = Path.GetExtension(data.Picture.FileName);
                        string fileName = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                        string savePath = Server.MapPath("~/Pictures/") + fileName;
                        data.Picture.SaveAs(savePath);
                        a.Picture = fileName;
                    }
                    db.Qualifications.RemoveRange(db.Qualifications.Where(x => x.ApplicantId == data.ApplicantId).ToList());
                    foreach (var item in data.Qualifications)
                    {
                        a.Qualifications.Add(new Qualification
                        {
                            ApplicantId = data.ApplicantId,
                            Degree = item.Degree,
                            Institute = item.Institute,
                            PassingYear = item.PassingYear,
                            Result = item.Result
                        });
                    }
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(data);
        }
        public ActionResult Delete(int id)
        {
            var sql = $"SELECT * FROM Applicants WHERE ApplicantId={id}";
            var a= db.Applicants.SqlQuery(sql).FirstOrDefault();
            sql = $"SELECT * FROM Qualifications WHERE ApplicantId={id}";
            a.Qualifications = db.Qualifications.SqlQuery(sql).ToList();

            return View(a);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DoDelete(int id)
        {
            var sql = $"DELETE  FROM Applicants WHERE ApplicantId={id}";
            int ra = db.Database.ExecuteSqlCommand(sql);

            return RedirectToAction("Index");
        }
        
    }
}

Exam/R54_Ex_06_Mvc_Evidence/R54_Ex_06_Mvc_Evidence/Views/Applicants/Create.cshtml
@model R54_Ex_06_Mvc_Evidence.ViewModels.ApplicantViewModel
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-12">
        @using (Html.BeginForm("Create", "Applicants", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <h3 class="mb-2">Add new appicant</h3>
            @Html.Partial("_ApplicantPartial", Model)
            
            <div class="col-12">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Degree</th>
                            <th>Institute</th>
                            <th>Passing year</th>
                            <th>Result</th>
                            <th>
                                <button type="submit" class="btn btn-secondary btn-sm" name="act" value="add" formnovalidate>Add</button>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (var i = 0; i < Model.Qualifications.Count; i++)
                        {
                            <tr>
                                <td>
                                    @Html.TextBoxFor(x => Model.Qualifications[i].Degree, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => Model.Qualifications[i].Degree, "", new { @class = "text-danger" })
                                   
                                </td>
                                <td>
                                    @Html.TextBoxFor(x => Model.Qualifications[i].Institute, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => Model.Qualifications[i].Institute, "", new { @class = "text-danger" })
                                </td>
                                <td>
                                    @Html.TextBoxFor(x => Model.Qualifications[i].PassingYear, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => Model.Qualifications[i].PassingYear, "", new { @class = "text-danger" })
                                </td>
                                <td>
                                    @Html.TextBoxFor(x => Model.Qualifications[i].Result, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => Model.Qualifications[i].Degree, "", new { @class = "text-danger" })
                                </td>
                                <th>
                                    <button type="submit" class="btn btn-secondary btn-sm" name="act" value="remove_@i" formnovalidate>Remove</button>
                                </th>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
            <div class="form-group row mb-1">

                <div class="col-12 text-end">
                    <button type="submit" class="btn btn-primary" name="act" value="insert">Save to database</button>
                </div>
            </div>
        }
    </div>
    
</div>
@section scripts {
    @Html.Partial("_scripts")    
}

Exam/R54_Ex_06_Mvc_Evidence/R54_Ex_06_Mvc_Evidence/Views/Applicants/Delete.cshtml
@model R54_Ex_06_Mvc_Evidence.Models.Applicant
@{
    ViewBag.Title = "Delete";
    var a = Model;
}

<div class="row">
    <div class="col-12">
        <h3>Are you sure to delete</h3>
       
        <table class="table table-bordered table-striped">
            <thead class="table-light">
                <tr>
                    <th></th>
                    <th>Applicant Name</th>
                    <th>Gender</th>
                    <th>Birth Date</th>
                    <th>Ready to work anywhere?</th>
                   
                </tr>
            </thead>
            <tbody>
               
                    <tr style="vertical-align:middle">
                        <td><img src="~/Pictures/@a.Picture" class="img-thumbnail rounded-circle" style="width:50px" /></td>
                        <td>@a.ApplicantName</td>
                        <td>@a.Gender</td>
                        <td>@a.BirthDate.ToString("yyyy-MM-dd")</td>
                        <td>@(a.IsReadyToWorkAnyWhere ? "Yes": "No")</td>
                       
                    </tr>
                    <tr>
                        <td></td>
                        <td colspan="5">
                            <h4>Qualifications</h4>
                            <table class="table table-bordered">
                                <thead class="table-light">
                                    <tr>
                                        <th>Degree</th>
                                        <th>Institute</th>
                                        <th>Passing year</th>
                                        <th>Result</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var q in Model.Qualifications)
                                    {
                                        <tr>
                                            <td>@q.Degree</td>
                                            <td>@q.Institute</td>
                                            <td>@q.PassingYear</td>
                                            <td>@q.Result</td>

                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </td>
                    </tr>
                
            </tbody>
        </table>
        @using (Html.BeginForm())
            {
                @Html.HiddenFor(x => x.ApplicantId);
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-danger">Confirm Delete</button>
            </div>
            }
    </div>
</div>

Exam/R54_Ex_06_Mvc_Evidence/R54_Ex_06_Mvc_Evidence/Views/Applicants/Edit.cshtml
@model R54_Ex_06_Mvc_Evidence.ViewModels.ApplicantEditModel
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-10">
        @using (Html.BeginForm("Edit", "Applicants", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(x => x.ApplicantId)
            <h3 class="mb-2">Add new appicant</h3>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.ApplicantName, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-6">
                    @Html.TextBoxFor(x => x.ApplicantName, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.ApplicantName, "", new { @class = "text-danger", style = "font-size:x-small" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Gender, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-6">
                    @Html.EnumDropDownListFor(x => x.Gender, new { @class = "form-select form-select-sm" })
                    @Html.ValidationMessageFor(x => x.Gender, "", new { @class = "text-danger", style = "font-size:x-small" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.BirthDate, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-6">
                    @Html.TextBoxFor(x => x.BirthDate, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.BirthDate, "", new { @class = "text-danger", style = "font-size:x-small" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.AppliedFor, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-6">
                    @Html.TextBoxFor(x => x.AppliedFor, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.AppliedFor, "", new { @class = "text-danger", style = "font-size:x-small" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-6">
                    @Html.TextBoxFor(x => x.Picture, new { @class = "form-control form-control-sm", type = "file" })
                    @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger", style = "font-size:x-small" })
                </div>
            </div>


            <div class="col-12">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Degree</th>
                            <th>Institute</th>
                            <th>Passing year</th>
                            <th>Result</th>
                            <th>
                                <button type="submit" class="btn btn-secondary btn-sm" name="act" value="add" formnovalidate>Add</button>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (var i = 0; i < Model.Qualifications.Count; i++)
                        {
                            <tr>
                                <td>
                                    @Html.TextBoxFor(x => Model.Qualifications[i].Degree, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => Model.Qualifications[i].Degree, "", new { @class = "text-danger" })

                                </td>
                                <td>
                                    @Html.TextBoxFor(x => Model.Qualifications[i].Institute, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => Model.Qualifications[i].Institute, "", new { @class = "text-danger" })
                                </td>
                                <td>
                                    @Html.TextBoxFor(x => Model.Qualifications[i].PassingYear, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => Model.Qualifications[i].PassingYear, "", new { @class = "text-danger" })
                                </td>
                                <td>
                                    @Html.TextBoxFor(x => Model.Qualifications[i].Result, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => Model.Qualifications[i].Degree, "", new { @class = "text-danger" })
                                </td>
                                <th>
                                    <button type="submit" class="btn btn-secondary btn-sm" name="act" value="remove_@i" formnovalidate>Remove</button>
                                </th>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
            <div class="form-group row mb-1">

                <div class="col-12 text-end">
                    <button type="submit" class="btn btn-primary" name="act" value="update">Save to database</button>
                </div>
            </div>
        }
    </div>
    <div class="col-2">

        <img src="~/Pictures/@ViewBag.CurrentPic" class="img-thumbnail" style="width:120px" />

    </div>
</div>
@section styles
{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts {
    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>
        $("#BirthDate").datepicker({
            format:"yyyy-mm-dd"
        })
    </script>
}

Exam/R54_Ex_06_Mvc_Evidence/R54_Ex_06_Mvc_Evidence/Views/Applicants/Index.cshtml
@model IEnumerable<R54_Ex_06_Mvc_Evidence.Models.Applicant>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-12">
        <h3>Employee List</h3>
        <div class="d-flex justify-content-end mb-1">


            <a href="@Url.Action("Create", "Applicants")" class="btn btn-primary btn-sm">Create New</a>
        </div>
        <table class="table table-bordered table-striped">
            <thead class="table-light">
                <tr>
                    <th></th>
                    <th>Applicant Name</th>
                    <th>Gender</th>
                    <th>Birth Date</th>
                    <th>Ready to work anywhere?</th>
                    <th>...</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var a in Model)
                {
                    <tr style="vertical-align:middle">
                        <td><img src="~/Pictures/@a.Picture" class="img-thumbnail rounded-circle" style="width:50px" /></td>
                        <td>@a.ApplicantName</td>
                        <td>@a.Gender</td>
                        <td>@a.BirthDate.ToString("yyyy-MM-dd")</td>
                        <td>@(a.IsReadyToWorkAnyWhere ? "Yes": "No")</td>
                        <td>
                            <a href="@Url.Action("Edit", "Applicants", new {id=a.ApplicantId})" class="btn btn-success btn-sm">Edit</a>
                            <a href="@Url.Action("Delete", "Applicants", new {id=a.ApplicantId})" class="btn btn-danger btn-sm del">Delete</a>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td colspan="5">
                            <h4>Qualifications</h4>
                            <table class="table table-bordered">
                                <thead class="table-light">
                                    <tr>
                                        <th>Degree</th>
                                        <th>Institute</th>
                                        <th>Passing year</th>
                                        <th>Result</th>
                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach(var q in a.Qualifications)
                                    {
                                        <tr>
                                            <td>@q.Degree</td>
                                            <td>@q.Institute</td>
                                            <td>@q.PassingYear</td>
                                            <td>@q.Result</td>
                                            
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@section scripts {
    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script>
        //$(".del").click(ev => {
        //    if (!confirm("Are you sure to delete?")) ev.preventDefault();
        //});
    </script>
}

Exam/R54_Ex_06_Mvc_Evidence/R54_Ex_06_Mvc_Evidence/Views/Applicants/_ApplicantEditPartial.cshtml
@model R54_Ex_06_Mvc_Evidence.ViewModels.ApplicantEditModel
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.ApplicantName, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.ApplicantName, new { @class = "form-control form-control-sm" })
        @Html.ValidationMessageFor(x => x.ApplicantName, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Gender, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.EnumDropDownListFor(x => x.Gender, new { @class = "form-select form-select-sm" })
        @Html.ValidationMessageFor(x => x.Gender, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.BirthDate, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.BirthDate, new { @class = "form-control form-control-sm", type = "date" })
        @Html.ValidationMessageFor(x => x.BirthDate, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.AppliedFor, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.AppliedFor, new { @class = "form-control form-control-sm" })
        @Html.ValidationMessageFor(x => x.AppliedFor, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.Picture, new { @class = "form-control form-control-sm", type = "file" })
        @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>

Exam/R54_Ex_06_Mvc_Evidence/R54_Ex_06_Mvc_Evidence/Views/Applicants/_ApplicantPartial.cshtml
@model R54_Ex_06_Mvc_Evidence.ViewModels.ApplicantViewModel
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.ApplicantName, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.ApplicantName, new { @class = "form-control form-control-sm" })
        @Html.ValidationMessageFor(x => x.ApplicantName, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Gender, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.EnumDropDownListFor(x => x.Gender, new { @class = "form-select form-select-sm" })
        @Html.ValidationMessageFor(x => x.Gender, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.BirthDate, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.BirthDate, new { @class = "form-control form-control-sm", type = "date" })
        @Html.ValidationMessageFor(x => x.BirthDate, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.AppliedFor, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.AppliedFor, new { @class = "form-control form-control-sm" })
        @Html.ValidationMessageFor(x => x.AppliedFor, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.Picture, new { @class = "form-control form-control-sm", type = "file" })
        @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>